// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG0iSUo91uBMfldj2lVr3-nvrohSl3guA',
    appId: '1:844033038493:web:35ca1a46133ffa21ee5c74',
    messagingSenderId: '844033038493',
    projectId: 'fir-project-2c152',
    authDomain: 'fir-project-2c152.firebaseapp.com',
    storageBucket: 'fir-project-2c152.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ZyJF9ZZ73AB1idduxefnWugc-VfYSGk',
    appId: '1:844033038493:android:b3eb8206e730e31dee5c74',
    messagingSenderId: '844033038493',
    projectId: 'fir-project-2c152',
    storageBucket: 'fir-project-2c152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3kb5oGJI97q6RYcezw-aKYxpI3z8WKGs',
    appId: '1:844033038493:ios:7e1b227f03e6d6b8ee5c74',
    messagingSenderId: '844033038493',
    projectId: 'fir-project-2c152',
    storageBucket: 'fir-project-2c152.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3kb5oGJI97q6RYcezw-aKYxpI3z8WKGs',
    appId: '1:844033038493:ios:7e1b227f03e6d6b8ee5c74',
    messagingSenderId: '844033038493',
    projectId: 'fir-project-2c152',
    storageBucket: 'fir-project-2c152.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG0iSUo91uBMfldj2lVr3-nvrohSl3guA',
    appId: '1:844033038493:web:81b84f6c3754c398ee5c74',
    messagingSenderId: '844033038493',
    projectId: 'fir-project-2c152',
    authDomain: 'fir-project-2c152.firebaseapp.com',
    storageBucket: 'fir-project-2c152.firebasestorage.app',
  );

}